version: '3'
services:
    www:
        image: nginx:alpine
        volumes:
            - ./docker/backend/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./backend:/var/www/html/api
            # - ./frontend:/var/www/html/app
        ports:
            - 8080:80
        depends_on:
            - frontend
            - backend

    frontend:
        image: node:16-alpine
        working_dir: /app
        volumes:
            - ./frontend:/app
        environment:
            NODE_ENV: development
        command: "yarn serve"

    backend:
        build:
            context: docker/backend
        user: 1000:1000
        working_dir: /app
        volumes:
            - ./backend:/var/www/html/api

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: roomraccoon
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

    adminer:
        image: adminer
        restart: always
        ports:
        - 9001:8080
